### ISSUE TITLE
Multi-GPU training

### ISSUE THREAD

**Issue by deepaknlp** [CZWin32768/XNLG#6]
Hi @CZWin32768 ,

Thank you for sharing your code.
I wanted to use the model to generate cross-lingual text. Basically, I am trying to load this XLM [model](https://dl.fbaipublicfiles.com/XLM/mlm_17_1280.pth) to fine-tune using the script `xnlg-ft.py`. I am getting the following errors:

```
Impossible to import FAISS library!!
Switching to standard nearest neighbors search implementation, this will be significantly slower.
SLURM job: False
1 - Number of nodes: 1`
1 - Node ID        : 0
1 - Local rank     : 1
1 - Global rank    : 1
1 - World size     : 3
1 - GPUs per node  : 3
1 - Master         : False
1 - Multi-node     : False
1 - Multi-GPU      : True
1 - Hostname       : nlp-server
Initializing PyTorch distributed ...
INFO - 02/17/20 22:14:52 - 0:00:00 - ============ Initialized logger ============
INFO - 02/17/20 22:14:52 - 0:00:00 - batch_size: 1
                                     beam_size: 3
                                     command: python xnlg/xnlg-ft.py --local_rank=1 --exp_name cmg --dump_path './dump' --model_path 'mlm_17_12
80.pth' --data_path './data/processed/XNLG' --transfer_tasks CM --optimizer 'adam,lr=0.000005' --batch_size 1 --n_epochs 200 --epoch_size 4000 
--max_len 40 --max_vocab 100000 --train_layers all --decode_with_vocab False --n_enc_layers 5 --n_dec_layers 5 --beam_size 3 --ds_name xcm --tr
ain_directions 'en-en' --eval_directions 'hi-hi' --multi_gpu True --tokens_per_batch 400 --exp_id "8k0nidys87"
                                     cut_dataset: -1
                                     data_path: ./data/processed/XNLG
                                     debug_slurm: False
                                     debug_train: False
                                     decode_vocab_sizes: 26000,20000
                                     decode_with_vocab: False
                                     dropout: 0
                                     ds_name: xcm
                                     dump_path: ./dump/cmg/8k0nidys87
                                     emb_dim: -1
                                     epoch_size: 4000
                                     eval_directions: hi-hi
                                     exp_id: 8k0nidys87
                                     exp_name: cmg
                                     finetune_layers: 0:_1
                                     fixed_embeddings: False
                                     fixed_lang_embeddings: False
                                     fixed_position_embeddings: False
                                     fixed_task_embeddings: False
                                     global_rank: 1
                                     group_by_size: False
                                     is_master: False
                                     is_slurm_job: False
                                     local_rank: 1
                                     master_port: -1
                                     max_batch_size: 0
                                     max_dec_len: 80
                                     max_len: 40
                                     max_len_a: 256
                                     max_len_e: 256
                                     max_len_q: 256
                                     max_vocab: 100000
                                     min_count: 0
                                     model_path: mlm_17_1280.pth
                                     multi_gpu: True
                                     multi_node: False
                                     n_dec_layers: 5
                                     n_enc_layers: 5
                                     n_epochs: 200
                                     n_gpu_per_node: 3
                                     n_nodes: 1
                                     no_init: None
                                     node_id: 0
                                     optimizer: adam,lr=0.000005
                                     optimizer_e: adam,lr=0.0001
                                     optimizer_p: adam,lr=0.0001
                                     reload_emb: 
                                     sample_alpha: 0
                                     tokens_per_batch: 400
                                     train_directions: en-en
                                     train_layers: all
                                     transfer_tasks: CM
                                     vocab_path: 
                                     weighted_training: False
                                     word_pred: 0.15
                                     world_size: 3
INFO - 02/17/20 22:14:52 - 0:00:00 - The experiment will be stored in ./dump/cmg/8k0nidys87
                                     
INFO - 02/17/20 22:14:52 - 0:00:00 - Running command: python xnlg/xnlg-ft.py --local_rank=1 --exp_name cmg --dump_path './dump' --model_path 'm
lm_17_1280.pth' --data_path './data/processed/XNLG' --transfer_tasks CM --optimizer 'adam,lr=0.000005' --batch_size 1 --n_epochs 200 --epoch_si
ze 4000 --max_len 40 --max_vocab 100000 --train_layers all --decode_with_vocab False --n_enc_layers 5 --n_dec_layers 5 --beam_size 3 --ds_name 
xcm --train_directions 'en-en' --eval_directions 'hi-hi' --multi_gpu True --tokens_per_batch 400
INFO - 02/17/20 22:16:13 - 0:01:27 - Supported languages: ar, de, en, es, fr, hi, it, ja, ko, nl, pl, pt, ru, sv, tr, vi, zh
INFO - 02/17/20 22:16:30 - 0:01:42 - Supported languages: ar, de, en, es, fr, hi, it, ja, ko, nl, pl, pt, ru, sv, tr, vi, zh
INFO - 02/17/20 22:16:36 - 0:01:44 - Supported languages: ar, de, en, es, fr, hi, it, ja, ko, nl, pl, pt, ru, sv, tr, vi, zh
Traceback (most recent call last):
  File "xnlg/xnlg-ft.py", line 348, in <module>
    run_xnlg()
  File "xnlg/xnlg-ft.py", line 343, in run_xnlg
    XCM(encoder, decoder, scores, dico, params).run()
  File "/home1/deepak/Documents/XNLG/xnlg/src/evaluation/xcm.py", line 193, in run
    self.encoder.cuda()
  File "/home1/deepak/anaconda/envs/unilm/lib/python3.6/site-packages/torch/nn/modules/module.py", line 260, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home1/deepak/anaconda/envs/unilm/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/home1/deepak/anaconda/envs/unilm/lib/python3.6/site-packages/torch/nn/modules/module.py", line 193, in _apply
    param.data = fn(param.data)
  File "/home1/deepak/anaconda/envs/unilm/lib/python3.6/site-packages/torch/nn/modules/module.py", line 260, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA out of memory. Tried to allocate 976.62 MiB (GPU 0; 10.91 GiB total capacity; 1.07 GiB already allocated; 844.44 MiB free; 1
08.00 KiB cached)
```
I also tried with multiple GPU but could not be able to load the model. Please help me in this regard.

**Comment by CZWin32768** [comment]
It shows an OOM exception. Have you tried a smaller batch size?

**Comment by deepaknlp** [comment]
Yes, I tried even with batch size 4. How much GPU memory your model used to fine-tune on a particular task?

**Comment by CZWin32768** [comment]
We have run the script on 16GB P100 or 16GB V100.
