### ISSUE TITLE
Assertion error in evalaution

### ISSUE THREAD

**Issue by deepaknlp** [CZWin32768/XNLG#7]
Hi @CZWin32768 ,

I am getting the following error on this line:
https://github.com/CZWin32768/XNLG/blob/58b1311192ac91e5dbbd6489496a3ffd4bd0e2c2/xnlg/src/evaluation/evaluator.py#L241

```
Traceback (most recent call last):
  File "xnlg/xnlg-train.py", line 336, in <module>
    main(params)
  File "xnlg/xnlg-train.py", line 304, in main
    scores = evaluator.run_all_evals(trainer)
  File "/home1/deepak/Documents/XNLG/xnlg/src/evaluation/evaluator.py", line 241, in run_all_evals
    self.evaluate_mt(scores, data_set, lang1, lang2, eval_bleu)
  File "/home1/deepak/Documents/XNLG/xnlg/src/evaluation/evaluator.py", line 489, in evaluate_mt
    generated, lengths = decoder.generate(enc1, len1, lang2_id, max_len=max_len)
  File "/home1/deepak/Documents/XNLG/xnlg/src/model/transformer.py", line 521, in generate
    assert tensor.size() == (1, bs, self.dim), (cur_len, max_len, src_enc.size(), tensor.size(), (1, bs, self.dim))
AssertionError: (2, 14, torch.Size([16, 3, 768]), torch.Size([2, 16, 768]), (1, 16, 768))
```
Here is the hyper-parameters that I am using:

```
export NGPU=1; python -m torch.distributed.launch --nproc_per_node=$NGPU  xnlg/xnlg-train.py \
--exp_name stage2_en-hi \
--dump_path ./dump \
--data_path ./data/processed/XNLG \
--lgs 'en-hi'  \
--mt_steps 'en-hi'  \
--ae_steps ''   \
--reload_model ./dump/stage1_en-hi/hacz7m10yz/best-valid_en_hi_mlm_ppl.pth,./dump/stage1_en-hi/hacz7m10yz/best-valid_en_hi_mlm_ppl.pth \
--emb_dim 768  \
--n_layers 4  \
--n_heads 8 \
--dropout 0.1 \
--attention_dropout 0.1 \
--gelu_activation True \
--batch_size 16 \
--bptt 128 \
--optimizer adam_inverse_sqrt,beta1=0.9,beta2=0.98,lr=0.0001  \
--epoch_size 10000 \
--max_vocab 120000 \
--encoder_only False  \
--train_model_names decoder  \
--stopping_criterion 'valid_en-hi_mt_bleu,25'   \
--validation_metrics 'valid_en-hi_mt_bleu'  \
--eval_bleu True  \
--word_shuffle 0  \
--word_dropout 0 \
--word_blank 0 \
--lambda_ae 0.5  \
--n_enc_layers 4 \
--fp16 True \
--amp 2 
```

I request to kindly see it and help me out.

**Comment by CZWin32768** [comment]
I guess it is caused by `ms2s` was unexpectedly set as True according to some bugs.
`ms2s` is a deprecated feature of  MultiHeadAttention.
Try to set the `ms2s` of a  MultiHeadAttention object as False.

set `self.ms2s=False` at
https://github.com/CZWin32768/XNLG/blob/58b1311192ac91e5dbbd6489496a3ffd4bd0e2c2/xnlg/src/model/transformer.py#L158

**Comment by deepaknlp** [comment]
Thank you @CZWin32768  for the quick reply. I will update you regarding this.
